plugins {
    id 'com.android.application'
}

android {
    namespace 'ie.udaltsoft.musicwatch'
    compileSdk 35

    defaultConfig {
        applicationId "ie.udaltsoft.musicwatch"
        minSdk 34 // Required for WFF v2
        targetSdkVersion 35
        versionCode 25
        versionName '2.50'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // Pure WFF projects do not need any dependencies. 
    // They are fully declarative XML-based packages.
}
